// Code generated by data/registry/generate.go; DO NOT EDIT.

package registryid

var TicketType = []string{
	"minecraft:start",
	"minecraft:dragon",
	"minecraft:player_loading",
	"minecraft:player_simulation",
	"minecraft:forced",
	"minecraft:portal",
	"minecraft:ender_pearl",
	"minecraft:unknown",
}
